name: Publish

on: 
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # shrink the files
    - name: replace js and css files with minified ones
      uses: nizarmah/auto-minify@v3
      with:
        overwrite: true
        js_engine: 'uglify-js'

    # get part of the tag after the `v`
    - name: Extract tag version number
      id: get_version
      uses: battila7/get-version-action@v2

    # Substitute the Manifest and Download URLs in the module.json
    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'module.json'
      env:
        version: ${{steps.get_version.outputs.version-without-v}}
        url: https://github.com/${{github.repository}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
        download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/module.zip
        changelog: https://github.com/${{github.repository}}/blob/${{github.event.release.tag_name}}/ChangeLog.md
        bugs: https://github.com/${{github.repository}}/issues
        readme: https://github.com/${{github.repository}}/blob/${{github.event.release.tag_name}}/README.md
        license: https://github.com/${{github.repository}}/blob/${{github.event.release.tag_name}}/LICENSE

    # Create a zip file with all files required by the module to add to the release
    - run: zip -r ./module.zip module.json README.md LICENSE ChangeLog.md scripts/ styles/ languages/ templates/

    # Create a release for this specific version
    - name: Update Release with Files
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # Set this to false if you want to prevent updating existing releases
        name: ${{ github.event.release.name }}
        draft: ${{ github.event.release.draft }}
        prerelease: ${{ github.event.release.prerelease }}
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json, ./module.zip'
        tag: ${{ github.event.release.tag_name }}
        body: ${{ github.event.release.body }}
